name: connect4
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.9             # PSF
  - pip==21.1.2             # MIT
  - pip:
    - isort==5.8.0          # MIT
    - autoflake==1.4        # MIT
    - black==21.5b2         # MIT
    - pytest==6.2.4         # MIT